alias G=g
alias ac=acroread
alias ac2=evince
alias an='~/bin/putanno.pl'
alias ap=add_to_path
alias av='~/projects/visionworkbench/src/vw/gui/vwv'
alias bm='~/projects/astrobee_build/devel/lib/sparse_mapping/build_map -output_map'
alias bmi='ASTROBEE_ROBOT=queen ~/projects/astrobee/devel/lib/sparse_mapping/build_map -info -output_map'
alias buf='stdbuf -o 0'
alias c=clear
alias c2s='~/bin/syncSettings.sh'
alias ca='conda activate'
alias caa='init_conda_zsh; conda activate asp_deps'
alias calib='cd $HOME/projects/ctx_calib'
alias car='cat run.sh'
alias cav='cat ./validate.sh'
alias cc='~/projects/CloudCompare/build/ccViewer/ccViewer'
alias ccv=/home/oalexan1/projects/CloudCompare/install/bin/CloudCompare
alias cd=cdls
alias cd1='cd ~/projects/20220617_Isaac10'
alias cd11='cd $HOME/projects/20220711_Isaac11'
alias cd2='cd $HOME/projects/2019-05-23'
alias cd3='cd $HOME/projects/dense3d'
alias cd32='cd $HOME/projects/dense3d/granite2'
alias cd4='cd $HOME/projects/oblique45'
alias cd5='cd $HOME/projects/dense3d/granite5'
alias cd6='cd $HOME/projects/dense3d/granite6'
alias cd7='cd $HOME/projects/kh7'
alias cda='cd $HOME/projects/atlanta'
alias cda2='cd $HOME/projects/albedo2'
alias cdah='cd $HOME/projects/as17_hasselblad'
alias cdaq='cd ~/"Library/Preferences/Aquamacs Emacs"'
alias cdas='cd $HOME/projects/aster/BasaltHills'
alias cdb='cd $HOME/projects/large_kaguya/narrow_bad'
alias cdb2='cd /srv/data1/oalexan1/bumble_20210223'
alias cdbb='cd $HOME/projects/BinaryBuilder'
alias cdbc='cd $HOME/bin/cpp'
alias cdbh='cd $HOME/projects/bsharp_20211118'
alias cdbin='cd $HOME/bin'
alias cdbl='cd $HOME/projects/base_system/lib'
alias cdbo='cd $HOME/projects/StereoPipeline/docs'
alias cdbp='cd $HOME/projects/BPR_20210604'
alias cdbr='cd $HOME/projects/skybox/Breckenridge'
alias cdbs='cd ~/projects/base_system'
alias cdbu='cd $HOME/projects/blacksky/Utqiagvik_20220425_stereo'
alias cdbw='cd $HOME/projects/visionworkbench$BASE/src/vw'
alias cdc='cd $HOME/projects/change3'
alias cdc2='cd $HOME/projects/conv2'
alias cdc3='cd $HOME/projects/WV01_11JAN13165'
alias cdca='cd $HOME/projects/ctx_calib'
alias cdcb='cd $HOME/projects/cambot'
alias cdcc='cd $HOME/projects/csm/ctx/stereo_images'
alias cdco='cd $HOME/projects/StereoPipeline$BASE/src/asp/Core'
alias cdcp='cd $HOME/bin/cpp'
alias cdd='cd $HOME/projects/dart_veg_20250118'
alias cddd='cd $HOME/projects/dart'
alias cdde='cd $HOME/Desktop'
alias cddg='cd $HOME/projects/dgkm'
alias cddi='cd $HOME/projects/data/icebridge'
alias cddo='cd $HOME/Downloads'
alias cddp='cd ~/bin/cpp/qt/drawpoly'
alias cddr='\cd $DR'
alias cdds='cd $HOME/projects/data/stereo_antarctic'
alias cddv='cd $HOME/projects/dart_veg_20250118'
alias cddw='cd $HOME/projects/data/WV01_11JAN13165'
alias cde='cd $HOME/projects/data/sfs_europa'
alias cdeg='cd $HOME/projects/GEOID09'
alias cdek='cd $HOME/projects/StereoPipeline/build'
alias cdf='cd $HOME/projects/sfs_ridge'
alias cdfa='cd $HOME/freeflyer/submodules/android'
alias cdfb='cd $HOME/projects/florida_bathy'
alias cdfs='cd $HOME/freeflyer/submodules/android/gs_examples/sci_cam_image'
alias cdg='cd $HOME/projects/GM_20191019'
alias cdg2='cd $HOME/projects/jitter_GM_20160925'
alias cdgm='cd $HOME/projects/GM_20191019'
alias cdh='cd $HOME/projects/hotsat'
alias cdh1='cd $HOME/projects/csm/hr1'
alias cdh2='cd $HOME/projects/csm/hr2'
alias cdi='cd $HOME/projects/ISIS3'
alias cdib='cd $HOME/projects/ISIS3/build'
alias cdj='cd $HOME/projects/ganymede_junocam'
alias cdk='cd $HOME/projects/large_kaguya'
alias cdk1='cd $HOME/projects/StereoPipeline$BASE/data/K10'
alias cdkc='cd $HOME/projects/csm/kc'
alias cdl='cd $HOME/projects/lunamaps'
alias cdl1='cd $HOME/projects/csm/lro1'
alias cdl2='cd $HOME/projects/csm/lro2'
alias cdl3='cd $HOME/projects/csm/lro3'
alias cdla='cd $HOME/Documents/albedo/laser10_2012_final_report'
alias cdlb='cd $HOME/projects/libpointmatcher/build'
alias cdlp='cd $HOME/projects/libpointmatcher'
alias cdm='cd $HOME/projects/MultiView'
alias cdm2='cd $HOME/projects/mgtf2'
alias cdmath='cd $HOME/projects/visionworkbench$BASE/src/vw/Math'
alias cdmg='cd $HOME/projects/mgru-viper-asp'
alias cdmp='cd $HOME/projects/mapProjection/DG_Map_Projection'
alias cdmv='cd $HOME/projects/mgru-viper-asp'
alias cdn='cd $HOME/projects/nobile_7.0'
alias cdn2='cd $HOME/projects/nobile_2'
alias cdnn='cd $HOME/projects/PleiadesNEO'
alias cdo='cd $HOME/projects/ortho_ready'
alias cdo5='cd $HOME/projects/oblique45'
alias cdol='cd /home1/oalexan1'
alias cdop='cd $HOME/projects/optical_dist'
alias cdp='cd $HOME/projects'
alias cdpa='cd $HOME/projects/20220608_Isaac9'
alias cdpc='cd $HOME/projects/cahvor'
alias cdpd='cd $HOME/projects/pdal/PDAL_latest'
alias cdpf='cd $HOME/projects/fft_match'
alias cdpg='cd $HOME/projects/PleiadesHR_GM_2020'
alias cdph='cd $HOME/projects/PhotometryTK'
alias cdpi='cd $HOME/projects/interp_bug'
alias cdpj='cd $HOME/projects/java'
alias cdpk='cd $HOME/projects/KH9_2016'
alias cdpm='cd ~/projects/cpp/polyView/gui'
alias cdpo='cd $HOME/projects/pasadena_OR2A_sample'
alias cdpp='cd $HOME/projects/PearyCrater2_GXP4'
alias cdpr='cd $HOME/projects/prism'
alias cdps='cd $HOME/projects/PeruSat'
alias cdpt='cd $HOME/projects/StereoPipelineTest'
alias cdpu='cd ~/projects/cpp/polyView/geom'
alias cdpv='cd $HOME/projects/PolyView'
alias cdpw='cd $HOME/projects/data/WV01_20110617'
alias cdpy='cd $HOME/projects/python'
alias cdr='cd $HOME/projects/MultiView/rig_calibrator'
alias cdrp='cd $HOME/projects/StereoPipeline$BASE/src/asp/Sessions/RPC'
alias cds='cd $HOME/projects/StereoPipeline'
alias cds2='cd $HOME/projects/astrobee/submodules/android/gs_examples/sci_cam_image2'
alias cdsa='cd $HOME/projects/StereoPipeline$BASE/src/asp'
alias cdsb='cd $HOME/projects/StereoPipeline'
alias cdsbb='cd $HOME/projects/StereoPipeline$BASE/src/asp'
alias cdsg='cd $HOME/projects/StereoPipeline/src/asp/GUI'
alias cdsi='cd $HOME/projects/StereoPipeline/src/asp/IceBridge'
alias cdsm='cd $HOME/projects/StereoPipeline$BASE/data/MOC'
alias cdso='cd $HOME/projects/sfs_south'
alias cdss='cd $HOME/projects/sfs'
alias cdst='cd ~smcmich1/projects/StereoPipelineTest'
alias cdsu='cd $HOME/projects/salar_de_uyni'
alias cdt='cd $HOME/projects/StereoPipeline$BASE/src/asp/Tools'
alias cdta='cd $HOME/projects/TanDEMX'
alias cdtb='$HOME/projects/PhotometryTK/build/src/tools'
alias cdtm='cd $HOME/projects/tests/moc'
alias cdtt='cd $HOME/projects/Tools'
alias cdu='cd $HOME/projects/umbra'
alias cdv='cd $HOME/projects/visionworkbench'
alias cdvt='cd $HOME/projects/visionworkbench$BASE/src/vw/tools'
alias cdw='cd $HOME/projects/dart/Weiwei010725'
alias cdwt='cd $HOME/projects/visionworkbench$BASE/src/vw/tools'
alias cdx='cd $HOME/projects/ctx_calib'
alias cdx2='cd $HOME/projects/data/CTX2'
alias cdxc='cd $HOME/projects/ctx_calib'
alias ce='crontab -e; crs'
alias ced='perl -pi -e "s#\s*\n#\n#g"'
alias cel='perl -pi -e "s#\s*\n#\n#g"'
alias ch='export HOST=$(uname -n); ca asp; cd $(pwd); cd $(pwd)'
alias chm='cd ~smcmich1/projects/StereoPipelineTest; chown -R :ar-gg-ti-asp-maintain .; chmod -R ug+rw .; \ls -altrd */* | grep -i oalexan1'
alias chpr='find . -type d -exec chmod u=rwx,go=rx {} +; find . -type f -exec chmod u=rw,go=r {} +'
alias ck='cd $HOME/projects/csm/kc'
alias cld='perl -p -e "s#(^.*?E).*(\s*)?\$#\$1\$2#g"'
alias clda='perl -p -e "s#(^.*?E).*(\s*)?\$#\$1.cal.echo.map.tif\$2#g"'
alias cll='perl -pi -e "s#.*?\]\s+:##g"'
alias cllog='perl -pi -e "s#.*?\]\s+:##g"'
alias cls='cd $HOME/projects/StereoPipeline; for f in $(llt src/asp/*/*{c,h} | tail -n 3 | ~/bin/print_col.pl 0); do ~/bin/clean_style.py $f; done'
alias cly='perl -pi -e "s#\[\w+\]##g" | perl -pi -e "s#\<\s*##g"'
alias cm=colormap.pl
alias cmd='cmx run/run-DEM.tif gold/run-DEM.tif'
alias cmi='~/bin/cmp_images.sh'
alias cmm='LD_LIBRARY_PATH=~/projects/BinaryBuilder/build_asp/install/lib:~/miniconda3/envs/asp/lib ASP_DEPS_DIR=~/miniconda3/envs/asp QT_PLUGIN_PATH=~/miniconda3/envs/asp/plugins GDAL_DATA=~/miniconda3/envs/asp PATH=~/projects/BinaryBuilder/build_asp/install/bin:~/miniconda3/envs/asp/bin:~/miniconda3/bin:~/miniconda3/condabin:~/projects/isis/bin:~/projects/BinaryBuilder/build_asp/install/bin:~/projects/BinaryBuilder/latest/bin:~/cmake_build/bin:~/projects/packages/bin:~/projects/freeflyer/build/bin:~/projects/StereoPipeline/src/asp/Tools:~/projects/visionworkbench/src/vw/tools:~/projects/packages/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin:/usr/local/bin:. colormap'
alias cmx='~/bin/cmp_images.sh x'
alias cn='rsync -avz -P --delete $M:projects/freeflyer/\* ~/projects/freeflyer/; cd ~/cmake_build; make -j 10'
alias code='~/projects/VSCode-linux-x64/bin/code'
alias cp='/bin/cp -vi'
alias cpdb='\cp -fv ~/bin/cpp/qt/drawpoly/drawpoly ~/bin'
alias cpl='cd  $HOME/projects/PhotometryTK/build; make -j 8 2>&1 |g error; cd $HOME/projects/PhotometryTK/build/src/tools; make reconstruct; cdpa '
alias cplo='cda; rf libvwPhotometry.la .libs/libvwPhotometry*; time make -j 10 2>&1 | grep -n -E --colour=auto error; cdt; rf reconstruct .libs/*reconstruct; touch reconstruct.cc; time make -j 10 reconstruct 2>&1 | g error; cdpa'
alias cpo='cdt; rf orthoproject .libs/*orthoproject; make orthoproject; cdpa'
alias cppv='\cp -fv ~/projects/cpp/polyView/gui/polyview ~/bin'
alias cpu='cat /proc/cpuinfo'
alias cr='chmod a+w -R'
alias crl='crontab -l'
alias crs='file=~/bin/crontab_$(hostname)".txt"; echo "Saving crontab to $file"; crontab -l > $file; tm $file'
alias cs=connect_to_screen.sh
alias csl='~/bin/clean_style.sh'
alias css='cvs status | grep -i status | grep -v "Up-to-date"'
alias cst='cvs status'
alias cva='cvs add'
alias cvc='cvs commit -m '
alias cvd='cvs diff'
alias cvr='cvs commit -m regolden'
alias cvu='cvs update -P -d'
alias cw='chmod u+w -R'
alias cx='chmod a+x'
alias db=disparitydebug
alias de=show_dems.pl
alias df='df -h'
alias dfg='df --block-size=1G'
alias dfm='df --block-size=1M'
alias dh='du -h'
alias di=diff.sh
alias dm=dem_mosaic
alias dma='dem_mosaic --max -o'
alias dp='display -resize "1016x740>" '
alias ds='du . | sort -n'
alias dt=diff_time.pl
alias e=eog
alias ebd='export BASE=_debug; echo BASE=$BASE; proml'
alias ebm='export BASE='
alias ebo='export BASE=; echo BASE=$BASE; proml'
alias ec=echo
alias ee=/home/oalexan1/projects/BinaryBuilder/StereoPipeline-2.6.2_post-2019-12-16-x86_64-Linux/bin/stereo_gui
alias egrep='egrep --color=auto'
alias el=elapsed.sh
alias elapse='grep elapsed= */output.txt | grep run.sh | perl -pi -e "s#\.\d+##g" | perl -pi -e "s#=# #g" | perl -pi -e "s#:#.#g" |tee output.txt'
alias elc='elapsed.sh CORR'
alias els='export LS_COLORS=""'
alias f3='~/bin/remote_copy.pl $C3 '
alias f32='~/bin/remote_copy.pl $C32 '
alias f5='~/bin/copy_from.pl $H5 '
alias f6='~/bin/remote_copy.pl $C6 '
alias fa2='~/bin/remote_copy.pl $A2 '
alias fb='~/bin/remote_copy.pl $B '
alias fba='cdpb; fb src; cdpa; fbh'
alias fbb='fb ~/bin/\*.\*'
alias fbc='fb \*.cc \*.h \*.sh'
alias fbh='fb \*.h \*.sh'
alias fbl='fb \*pl'
alias fbm='fb \*.m'
alias fbp='fb \*.p\*'
alias ff='~/projects/jitter_2020/find_bounds.sh'
alias ffi='ffprobe -show_entries stream=channels -v 0  -of compact=p=0:nk=1 -i'
alias fgrep='fgrep --color=auto'
alias fh='find . -name'
alias fii=float2int2.pl
alias fixdetachedhead='~/bin/fix_detached_head.sh'
alias fl='~/bin/remote_copy.pl oalexan1@laptop'
alias fl0='~/bin/remote_copy.pl oalexan1@laptop'
alias fl1='~/bin/remote_copy.pl $L1'
alias fl2='~/bin/remote_copy.pl $L2'
alias flb='fl ~/bin/\*.\*'
alias flh='fl \*sh'
alias flp='fl \*py'
alias fm='~/bin/remote_copy.pl $M '
alias fma='fm \*'
alias fmb='fm ~/bin/\*.\*'
alias fmc='fm \*.cc \*.h \*.sh'
alias fmh='fm \*sh'
alias fml='fm \*pl'
alias fmm='fm \*m'
alias fmp='fm \*.py'
alias fmu='fm ~/.muttrc; grep -i pass ~/.muttrc'
alias fp='~/bin/remote_copy.pl oalexan1@pfx'
alias fsg='~/bin/remote_copy.pl $SG'
alias fw='~/bin/remote_copy.pl oalexan1@wow'
alias fwh='fw \*sh'
alias fz='~/bin/remote_copy.pl $Z '
alias g='grep --binary-files=text -n -i -E --colour=auto'
alias ga='git add'
alias gaa='git add $(gs |grep -v submodules |grep modified: | grep -v "new commits" | grep -v "modified content" | grep -v "untracked content" | pc 0 | unc)'
alias gab='geodiff --absolute  --csv-format "1:lat 2:lon 3:height_above_datum" '
alias gam='git add $(gs | grep modified | pc 2)'
alias gb='git rebase'
alias gb5='grep -B 5 -A 5'
alias gbo='git rebase origin/master'
alias gc='git checkout'
alias gca='grep -i -A 2 "convergence angle"'
alias gcl='export LD_LIBRARY_PATH=""; git clone '
alias gcp='git cherry-pick'
alias gd='git diff'
alias gda='gdb attach'
alias gdc='gdal_translate --config GDAL_CACHEMAX 2048 -ot UInt16 -co NBITS=16 -co bigtiff=if_safer -co tiled=yes -co compress=lzw'
alias gdd='gdal_translate -co compress=lzw -a_nodata -9999'
alias gdo='gdal_translate -co compress=lzw -a_nodata 0'
alias gdp='~/bin/gdal_translate.pl -projwin'
alias gds='gdal_translate.pl -srcwin'
alias gdt='~/bin/gdal_translate.pl'
alias genlist='cddr; rf list.html; for f in $(ls -ald -t * | pc 9 |grep -v list.html); do g=https://byss.arc.nasa.gov/oalexan1/$f/$f.kml; ec $g; ec "<p> <a href=$g>$g</a><br>" >> list.html; done'
alias geod='cd $HOME/projects/nobackup/geoid'
alias gf='gfortran -Wall -c'
alias gfa='git fetch --all'
alias gg=grep
alias gga='grep -i -A 2 "convergence angle"'
alias ggi='grep -i'
alias gi='gdalinfo -stats -proj4'
alias gi2=/byss/packages/gdal-1.8.1/bin/gdalinfo
alias gio='gdalinfo -stats'
alias gl='git lg'
alias glg='git lg'
alias glgs='git lg | head -n 20'
alias gm='git commit -m'
alias gmm='git commit -m minor'
alias gn='gnuclient -nw '
alias gp='git push origin master'
alias gpg='git push god master'
alias gpl=get_platform.py
alias gpm='git push origin main'
alias gps='git push'
alias grc='grep -i -A 2 convergence'
alias grep='grep --color=auto'
alias gs='git status'
alias gs2='git status | grep -v "\.\."'
alias gsc=gsc.sh
alias gsc10=gsc10.sh
alias gsm='git status | grep -E "modified:|file:|deleted:"'
alias gt='git difftool --tool=tkdiff'
alias gtc='gt $(gs |g rig | pc 0)'
alias gtf='gdal_translate -of GTiff'
alias gts='gdal_translate.pl -srcwin'
alias gu='git reset HEAD'
alias gw=gdal_win.sh
alias gwt='grep "Walltime Used"'
alias h='head -n'
alias h10='head -n 10'
alias h5='head -n 5'
alias hbb='head -n 1000'
alias hc='~/bin/history_command.py'
alias hd='hillshade --azimuth 300 --elevation 20 -s 0'
alias hi=history
alias hp='nohup nice -20'
alias hs='/usr/bin/head -n 10'
alias ht='head -n 5'
alias ic='~/bin/show_cube.sh'
alias ipconfig=ifconfig
alias iq=image2qtree.pl
alias is='. isis_setup.sh'
alias iv='identify -verbose'
alias iz=init_conda_zsh
alias k9='kill -9 -v'
alias ka='killall -v -9'
alias kl=make_kml.pl
alias km='killall -9 -v matlab; killall -9 -v MATLAB'
alias kn=kill_by_name.sh
alias kna='kn gcc sleep build python stereo launch_ stereo corr perl auto_build sleep g++ '
alias knp='kn python'
alias kns='kn stereo run point'
alias kp='kn python'
alias kra='for q in 1 2 4 5 ; do for h in oalexan1@lunokhod1 oalexan1@andey oalexan1@amos pipeline@centos-32-5 pipeline@centos-64-5 pipeline@ubuntu-64-13; do remote_copy.pl $(ls ~/bin/{kill_remote.sh,kill_by_name.sh,print_col.pl}) $h; ssh $h "export PATH=~/bin:$PATH; kill_by_name.sh autogen configure make gcc g++ fortran make sleep build launch_ perl python stereo time run test sed tar pbz validate auto" 2>/dev/null; done; done |tee output.txt'
alias ks='for f in $(ps ux |grep -E "rpc|stereo|run" | pc 2 |grep -v ps | grep -v grep); do kill -9 $f; done'
alias kv='killall -v Xvnc; killall -v gnome-keyring-daemon'
alias l='ls -a --color=auto'
alias l.='ls -d .* --color=auto'
alias la='find .'
alias lc='~/bin/lc.pl'
alias ldm='otool -L'
alias less=mymore
alias lgd='libtool --mode=execute gdb'
alias ll='ls -alh --color=auto'
alias lld='ls -alhd --color'
alias llh='ll -h'
alias llo='llt out*'
alias lls='ls -lSr -d -a -h --color'
alias lns='ln -s'
alias ls=ls
alias ls-l='ls -l'
alias lsd='ls -d *(/)'
alias lt=llt
alias lta='llt *'
alias m=mymore
alias m0='make -j 16'
alias m0c='ulimit -s unlimited; ulimit -f unlimited; ulimit -v unlimited; is; m0 check'
alias m0k='make -j 16 -k'
alias matlab='matlab -nosplash'
alias mb=/home/oalexan1/projects/meshlab/src/build/distrib/meshlab
alias mc='make clean'
alias md='mkdir -p'
alias mdc='make distclean'
alias me=max_err_v2.pl
alias mi='make install -j 10'
alias mk='time make'
alias mkl='pl "s#\/.*\/##g"'
alias mkt=make_kml_tiles.pl
alias ml='matlab -nosplash -nodesktop -nojvm'
alias mm='~/cmake_build/bin/build_map -info -output_map'
alias mv='/bin/mv -vi'
alias nano=vim
alias nb='nbquota nobackupp2'
alias ni='ninja install'
alias nv='~/projects/astrobee/devel/lib/sparse_mapping/nvm_visualize -skip_3d_points -skip_3d_images -enable_image_deletion'
alias nv3='~/projects/astrobee_build/bin/nvm_visualize -skip_3d_points'
alias nvm='~/projects/astrobee_build/bin/nvm_visualize -skip_3d_points -jump_to_3d_view -skip_3d_images'
alias o='top -u $(whoami)'
alias os=osgviewer
alias outenv='mkdir -p run; grep = output.txt |grep -v \* |grep -v env | perl -pi -e "s#^#export #g" |grep -vi ssh | grep -i -v \%d > run/tmp.txt; source run/tmp.txt'
alias p=vim
alias p0='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2000'
alias p00='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2000'
alias p01='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2001'
alias p02='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2002'
alias p1='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2100'
alias p10='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2100'
alias p11='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2101'
alias p12='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2102'
alias p2='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2200'
alias p20='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2000'
alias p21='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2001'
alias p22='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2200'
alias p3='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2300'
alias p30='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2300'
alias p31='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2301'
alias p32='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2302'
alias p4='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2400'
alias p40='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2400'
alias p41='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2401'
alias p42='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2402'
alias p5='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2500'
alias p50='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2500'
alias p51='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2501'
alias p52='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2502'
alias p6='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2600'
alias p60='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2600'
alias p61='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2601'
alias p62='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2602'
alias p7='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2700'
alias p70='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2700'
alias p71='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2701'
alias p72='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2702'
alias pa='ps aux'
alias pc=print_col.pl
alias pd=point2dem
alias pda='pd --tr 18 --stereographic --proj-lon 3.6357977 --proj-lat 25.4814476'
alias pdac='point2dem --t_srs "+proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs" --tr 0.4 --errorimage --csv-format 1:lat,2:lon,3:height_above_datum'
alias pdan='point2dem --t_srs "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs" --tr 0.4 --errorimage --csv-format 1:lat,2:lon,3:height_above_datum'
alias pde='point2dem --errorimage'
alias pdi='point2dem --tr 0.5 --t_srs +proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs --errorimage'
alias pdl='point2dem --t_srs "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs" --tr 1 --errorimage --csv-format 2:lat,1:lon,3:height_above_datum'
alias pdli='point2dem --t_srs "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs" --tr 1 --errorimage --csv-format 1:lat,2:lon,3:height_above_datum'
alias pdm='point2dem  -r mars --nodata-value -32768'
alias pds='point2dem  --t_srs "+proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs" --tr 1'
alias pdso='point2dem --errorimage --t_srs "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs" --csv-format "1:lat 2:lon 3:height_above_datum" --tr 0.4'
alias pe=' perl -MCPAN -e shell'
alias pico=vim
alias pl='perl -pi -e'
alias pll='perl -p -e "s#^.*?(M\d+\wE).*?\n#\$1\n#g"'
alias plr='perl -p -e "s#lnav#*nav#g" | perl -p -e "s#NLB#N*B#g" | perl -p -e "s#\s# #g"'
alias plt='perl -p -e "s#^.*?(\d+\.\d+).*?(\n)#\$1\$2#g"'
alias pm='point2mesh -s 4 --texture-step-size 1'
alias pp='python plot_mat.py'
alias ppd='~/miniconda3/envs/sparse_disp/bin/python ~/projects/jitter_2020/plot_disp.py --skip_moving_avg 1 --skip_output_gen 1 --exclude 0 --ylim 2 --clamp 2'
alias printfile='lpr -Pap185'
alias printfilecolor='lpr -Papc185'
alias prl='~/bin/proc_list.sh'
alias psc='vim ~/.ssh/config'
alias psmerge='echo ghostscript -dNOPAUSE -sDEVICE=pswrite -dBATCH -sOutputFile=out.ps part1.ps part2.ps part3.ps ...'
alias pso=psort
alias psp='~/bin/push_settings.sh pull m.ndc.nasa.gov; ~/bin/push_settings.sh centos-32-5 ubuntu-64-13 centos-64-5 amos andey'
alias pu='ps ux'
alias pucat='ps ux | cat'
alias puq='pu |grep qtree'
alias pv='perl -pi -e "s# run.txt# run/run.txt#g" validate.sh; perl -pi -e "s# gold.txt# gold/run.txt#g" validate.sh'
alias py=python
alias q='~/projects/isis/bin/qview'
alias qd=qdel
alias qda='qdel $(qs | grep $(whoami) | pc 1 | perl -pi -e "s#\.p\d+##g")'
alias qs='qstat -u $(whoami)'
alias qsa='qstat -a'
alias qsd='qstat devel@pbspl3 -u $(whoami)'
alias qt='quota -s'
alias qv='quota -v -s'
alias ra='rsa; cdb; m0; cdsb; m0'
alias rb='cd ../; rm -rfv build; md build; cd build'
alias rbi='rosbag info'
alias rbs='for f in ~/projects/StereoPipeline/src/asp/Tools/*; do g=$(basename $f); echo $g; rf ~/projects/base_system/bin/$g; done'
alias rc='~/bin/remote_copy.pl'
alias rcs='rm -rfv CVS */CVS'
alias rd=./run.sh
alias re='rostopic echo'
alias rel='lsb_release -a'
alias rf='\rm -fv'
alias rfco='rf core.*'
alias rfl='rm -fv *-log-*'
alias rflo='/bin/rm -fv *-log-*'
alias rfo='rm -fv *[0-9A-Za-z].o[0-9]* .#* java.log.* matlab_crash* .*~ *~  \#* server.slog print.prt'
alias rfou='rm -fv out*'
alias rfox='rm -fv .\#* \#* java.log.* matlab_crash* .*~ *~ *.box *.ly1 *.ly2 *.ly *.xg \#* server.slog .*swp ~/.zsh_history.*'
alias rft='rm -rfv *tmp*'
alias rfu='for f in $(gs |g -A 1000 Untrack | pc 0); do /bin/rm -rfv ./"$f"; done'
alias rg='rm -rfv gold; cp -rfv run gold'
alias rh='perl -pi -e "s#\/home\w*\/\w+#\\\$HOME#g" ~/.bash_aliases'
alias ri='rostopic info'
alias rl='rostopic list'
alias rm='/bin/rm -vi'
alias rmanno='perl -pi -e "s#anno.*?\n##g"'
alias rmc='perl -pi -e "s#^\s*\#.*?\n##g"'
alias rmco='perl -pi -e "s#^(\s+)(std::cout)#\$1\/\/\$2#g"'
alias rmco2='perl -pi -e "s#^.*?std::cout.*?\n##g"'
alias rmcol='perl -p -e "s#:.*?(\s)\$#\$1#g"'
alias rmcons=' perl -pi -e "s#^.*?\]\s*:\s*##g"'
alias rml='perl -pi -e "s#\([ ]+#\(#g"'
alias rmr=' perl -pi -e "s#\([ ]+#\(#g"'
alias rms='perl -pi -e "s#^.*?\*\*.*?\$##g"'
alias rmu='for f in $(git status |grep -A 1000 Untrack); do if [ ! -e "./$f" ]; then continue; fi; /bin/rm -rfv ./"$f"; done'
alias rmvw='for f in ~/projects/visionworkbench/src/vw/tools/* ~/projects/StereoPipeline/src/asp/Tools/*; do g=$(basename $f); echo $g; rf ~/projects/base_system/bin/$g; done; rm -rfv ~/projects/base_system/include/vw ~/projects/base_system/include/asp ~/projects/base_system/lib/libvw* ~/projects/base_system/lib/libasp*'
alias rp='rosbag play'
alias rpl='rosbag play'
alias rr=./run.sh
alias rs='rsync -avz -P'
alias rsa='~/bin/rsync.sh'
alias rsb='reset; sb'
alias rsl='reset; sl'
alias rsm='reset; sm'
alias rss=reset
alias rstest='rsync -avz -e "ssh -p 2002 oalexan1@localhost" ~/.xsession :'
alias rt=reset
alias run-help=man
alias rvv='rosrun rviz rviz'
alias s='reset; ssh lunokhod1 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -X 2>/dev/null'
alias s0='ssh pfe20'
alias s00='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2000'
alias s01='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2001'
alias s02='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2002'
alias s1='ssh oleg@localhost -p 6403'
alias s10='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2100'
alias s11='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2101'
alias s12='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2102'
alias s2='ssh pfe22'
alias s20='ssh pfe20'
alias s21='ssh pfe21'
alias s22='ssh pfe22'
alias s23='ssh pfe23'
alias s24='ssh pfe24'
alias s25='ssh pfe25'
alias s26='ssh pfe26'
alias s27='ssh pfe27'
alias s3='ssh centos-32-5'
alias s30='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2300'
alias s31='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2301'
alias s32='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2302'
alias s4='ssh ubuntu-64-13'
alias s40='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2400'
alias s41='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2401'
alias s42='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2402'
alias s5='ssh pfe25'
alias s50='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2500'
alias s51='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2501'
alias s52='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2502'
alias s6='ssh centos-6'
alias s60='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2600'
alias s61='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2601'
alias s62='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2602'
alias s7='ssh centos7 -l pipeline -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias s70='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2700'
alias s71='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2701'
alias s72='ssh localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2702'
alias s8='ssh pfe8'
alias s9='ssh pfe9'
alias sa='ssh mac_arm -l oalexan1'
alias sa2='ssh andey'
alias sas='ssh astrobee@10.42.0.32'
alias sb='s=StereoPipeline-3.4.0-alpha-2023-12-23-x86_64-Linux; add_to_path $HOME/projects/BinaryBuilder/$s/bin'
alias sb1='ssh bridge1'
alias sb2='ssh bridge2'
alias sb3='ssh bridge3'
alias sb4='ssh bridge4'
alias sbc='~/bin/sortbycol.pl'
alias sc='sg --colorize --min 0 --max 1'
alias sc10='sg --colorize --min 0 --max 10'
alias sc2='sortbycol.pl -1'
alias sc3='ssh centos-32-5'
alias sc6='ssh centos-64-5'
alias sd='ssh oalexan1@decoder'
alias se='ssh mfe1 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias setdate='sudo date -s "$(ssh $L2 date 2>/dev/null)"'
alias sg='stereo_gui --window-size 1500 1000 --font-size 12'
alias sg0='stereo_gui --window-size 1300 1400 --font-size 12 --lowest-resolution-subimage-num-pixels 1000000'
alias sg10='sg --colorize --min 0 --max 10'
alias sga='sg --single-window --hide-all'
alias sgc1='sg --colorbar --min 0 --max 1'
alias sgg=./StereoPipeline-None-2017-04-19-x86_64-Linux/bin/stereo_gui
alias sgh='sg --hillshade'
alias sgp='stereo_gui --create-image-pyramids-only'
alias sgp0='stereo_gui --preview --window-size 1300 1400 --font-size 12 --lowest-resolution-subimage-num-pixels 9000000'
alias sgph='stereo_gui --create-image-pyramids-only --hillshade'
alias sho='ssh $H -p 1979'
alias sis=sis.pl
alias sl='ssh laptop -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -X 2>/dev/null'
alias sl1='ssh lunokhod1 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -X 2>/dev/null'
alias sl2='ssh lunokhod2 -X 2>/dev/null'
alias sle='ssh lfe'
alias slf='ssh lfe'
alias sls='screen -ls'
alias sm='reset; ssh m.ndc.nasa.gov -l oalexan1 -X -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias smath='ssh tools-login.wmflabs.org -l mathbot'
alias smf=show_matchfile.sh
alias sn='reset; ssh m.ndc.nasa.gov -l oalexan1 -X -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias soff='perl -pi -e "s#\/*system\(#\/\/system(#g" *cc *.h'
alias son='perl -pi -e "s#\/*system\(#system(#g" *cc *.h'
alias sp='ssh pfx'
alias sp3='ssh pipeline@localhost -p 3250'
alias spc='spiceinit from = '
alias sps='system_profiler SPSoftwareDataType'
alias spx='ssh pfx'
alias sr='sup rsync -avz -T /tmp '
alias srs=see_res.sh
alias ss='ssh spherescheetah -l oalexan1 -X'
alias ss2='ssh spherescheetah -X'
alias ss7='ssh centos7'
alias ssa='reset; ssh astrobeast -X'
alias sse='ssh mfe1 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias ssw='reset; ssh wow -l oalexan1 -X'
alias st=./stereo.sh
alias start='ps -o lstart= -C '
alias su='ssh ubuntu14 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -X'
alias su6='ssh ubuntu-64-13'
alias super='echo lE7wzkPyf*qHf5nt'
alias sv='ssh volar -l oalexan1 -X'
alias sva='svn add'
alias svd='svn diff'
alias svdel='svn delete'
alias svl='svn log |less'
alias svm='svn commit -m '
alias svs='svn status --show-updates'
alias svu='svn update'
alias sw='sg -g -w'
alias sw0='sg0 -g -w'
alias swa='sg -w --hide-all'
alias swah='sg -g -w --hide-all --hillshade'
alias swh='sg -g -w --hillshade'
alias sx='screen -x'
alias t1='tail -n 1000'
alias t10='tail -n 10'
alias t5='tail -n 5'
alias tbb='tail -n 20000'
alias tbig='tail -n 10000'
alias tc='tar czfv'
alias ti='~/bin/toink.pl'
alias tk=tkdiff
alias tkn=tkn.sh
alias tks='~/bin/tksort.sh'
alias tn='tail -n'
alias tph='tp \*sh'
alias tpp='tp \*.p\*'
alias tt='tail -n 5'
alias u='cd ../'
alias ua='uname -a'
alias uct='ctest -R $f -V --timeout 1200 '
alias unc='~/bin/unique.pl'
alias uni='~/bin/unique.pl'
alias unmount='echo "Error: Try the command: umount" 1>&2; false'
alias unp='. ~/bin/unsetpath'
alias unq='~/bin/unique.pl'
alias unz=unz.sh
alias vd=vimdiff
alias ver='lsb_release -a'
alias ver2='system_profiler SPSoftwareDataType'
alias vg='valgrind --leak-check=full --log-file=log.txt --tool=memcheck'
alias vgp='valgrind --tool=callgrind --dump-instr=yes '
alias vi=vim
alias vk='valview --view-log'
alias vl=vi_line.sh
alias vls='virsh list --all'
alias vlv='valview --view-log'
alias vn5='vncviewer -FullColor localhost:5001'
alias vnc='vncserver -geometry 1292x996'
alias vnc2='vncserver -geometry 1700x1000'
alias vnc_home='vncserver -geometry 1750x1000'
alias vncbig='vncserver -geometry 2550x1008'
alias vncbig2='vncserver -geometry 2546x993'
alias vnp='ps ux |grep vnc | grep rfbport | perl -p -e "s#^.*?rfb(port\s+\d+).*?\n#vnc \$1\n#g"'
alias vnw='xvncviewer localhost:9007'
alias vo='~/bin/view_out.sh'
alias voff='perl -pi -e "s#AM_DEFAULT_VERBOSITY = 1#AM_DEFAULT_VERBOSITY = 0#g" Makefil*'
alias von='perl -pi -e "s#AM_DEFAULT_VERBOSITY = 0#AM_DEFAULT_VERBOSITY = 1#g" Makefile; g verb Makefile'
alias vr='. ~/bin/vr'
alias vs='~/projects/VSCode-linux-x64/bin/code-insiders'
alias vv=./validate.sh
alias w=which
alias wg=wget
alias which-command=whence
alias wp='which python'
alias wq='~/bin/wrap_quoted_text.py wqr $HOME/projects/StereoPipeline'
alias ww=/home/oalexan1/openMVS/build/bin/Viewer
alias x=exit
alias z=zsh
