(define-abbrev-table 'sh-mode-abbrev-table '(
    ))

(define-abbrev-table 'doctex-mode-abbrev-table '(
    ))

(define-abbrev-table 'javascript-mode-abbrev-table '(
    ))

(define-abbrev-table 'xrdb-mode-abbrev-table '(
    ))

(define-abbrev-table 'awk-mode-abbrev-table '(
    ("while" "while" c-electric-continued-statement 0)
    ("else" "else" c-electric-continued-statement 0)
    ))

(define-abbrev-table 'pike-mode-abbrev-table '(
    ("while" "while" c-electric-continued-statement 0)
    ("else" "else" c-electric-continued-statement 0)
    ))

(define-abbrev-table 'idl-mode-abbrev-table '(
    ))

(define-abbrev-table 'java-mode-abbrev-table '(
    ("finally" "finally" c-electric-continued-statement 0)
    ("while" "while" c-electric-continued-statement 0)
    ("else" "else" c-electric-continued-statement 0)
    ("catch" "catch" c-electric-continued-statement 0)
    ))

(define-abbrev-table 'objc-mode-abbrev-table '(
    ("while" "while" c-electric-continued-statement 0)
    ("else" "else" c-electric-continued-statement 0)
    ))

(define-abbrev-table 'winmgr-mode-abbrev-table '(
    ))

(define-abbrev-table 'matlab-shell-topic-mode-abbrev-table '(
    ))

(define-abbrev-table 'matlab-shell-help-mode-abbrev-table '(
    ))

(define-abbrev-table 'f90-mode-abbrev-table '(
    ("`mo" "module" nil 0)
    ("`it" "intent" nil 0)
    ("`ey" "entry" nil 0)
    ("`eli" "else if" nil 0)
    ("`ex" "external" nil 0)
    ("`r" "real" nil 0)
    ("`tr" ".true." nil 0)
    ("`pu" "public" nil 0)
    ("`im" "implicit none" nil 0)
    ("`fa" ".false." nil 0)
    ("`eq" "equivalence" nil 0)
    ("`pr" "print" nil 0)
    ("write" "write (*, *) " nil 3)
    ("`bd" "block data" nil 0)
    ("`i" "integer" nil 0)
    ("`as" "assignment" nil 0)
    ("`po" "pointer" nil 0)
    ("`ba" "backspace" nil 0)
    ("`el" "else" nil 0)
    ("`pm" "program" nil 0)
    ("`if" "interface" nil 0)
    ("`wr" "write" nil 0)
    ("`lo" "logical" nil 0)
    ("`c" "character" nil 0)
    ("`su" "subroutine" nil 0)
    ("`pi" "private" nil 0)
    ("`al" "allocate" nil 0)
    ("`dw" "do while" nil 0)
    ("`ta" "target" nil 0)
    ("`in " "include" nil 0)
    ("`sq" "sequence" nil 0)
    ("`wh" "where" nil 0)
    ("`pa" "parameter" nil 0)
    ("`op" "optional" nil 0)
    ("`ab" "allocatable" nil 0)
    ("`rw" "rewind" nil 0)
    ("`di" "dimension" nil 0)
    ("`se" "select" nil 0)
    ("`cy" "cycle" nil 0)
    ("`cx" "complex" nil 0)
    ("`rt" "return" nil 0)
    ("`df" "define" nil 0)
    ("`de" "deallocate" nil 0)
    ("`nu" "nullify" nil 0)
    ("`cn" "contains" nil 0)
    ("`cm" "common" nil 0)
    ("`cl" "close" nil 0)
    ("`elw" "elsewhere" nil 0)
    ("`fu" "function" nil 0)
    ("`rc" "recursive" nil 0)
    ("`fo" "format" nil 0)
    ("`fl" "forall" nil 0)
    ("print" "print *, \"\"" (lambda nil (interactive) (search-backward "\"")) 38)
    ("`na" "namelist" nil 0)
    ("`t" "type" nil 0)
    ))

(define-abbrev-table 'hm--html-mode-abbrev-table '(
    ("hh" "<hr />" nil 9)
    ("\\s" "&nbsp;" nil 1)
    (",," "<br>" nil 2)
    ("htat" "that " nil 2)
    ("\\prob" "<p /> <b>Problem .</b>" nil 2)
    ("teh" "the " nil 2)
    ("incl" "<!--#include virtual=\"\"-->" nil 1)
    ("\\hr" "<hr />" nil 2)
    ("pp" "<p /> " nil 33)
    (".." "&nbsp;" nil 7)
    ("bb" "<br />" nil 23)
    ("taht" "that " nil 7)
    ("wiht" "with " nil 1)
    ("\\ect" "</center>" nil 5)
    ("\\bct" "<center>" nil 1)
    ("\\ct" "<center></center>" (lambda nil (interactive) (search-backward "</")) 7)
    ))

(define-abbrev-table 'html-mode-abbrev-table '(
    ("hh" "<hr />" nil 7)
    ("\\s" "&nbsp;" nil 1)
    (",," "<br>" nil 2)
    ("htat" "that " nil 2)
    ("teh" "the " nil 28)
    ("hte" "the " nil 9)
    ("\\hr" "<hr />" nil 2)
    ("pp" "<p /> " nil 17)
    (".." "&nbsp;" nil 1)
    ("bb" "<br />" nil 19)
    ("taht" "that " nil 7)
    ("wiht" "with " nil 1)
    ("\\ect" "</center>" nil 5)
    ("\\bct" "<center>" nil 1)
    ("\\ct" "<center></center>" (lambda nil (interactive) (search-backward "</")) 7)
    ))

(define-abbrev-table 'matlab-mode-abbrev-table '(
    ("dsp" "disp(sprintf('%'));" (lambda nil (indent-according-to-mode) (search-backward "%")) 129)
    (";dl" "dlmread" nil 0)
    (";p" "plot(" nil 0)
    ("dsi" "display(sprintf('%d'))" nil 1)
    ("\\ch" "clf; hold on; axis equal; axis off;" nil 0)
    ("\\disp" "disp(sprintf('%d', ));" nil 1)
    ("\\fig" "figure()" backward-char 11)
    (";d" "dlmread" nil 0)
    ("sgf" "saveas(gcf, '')" nil 24)
    ("cho" "clf; hold on;" nil 1)
    ("for" "" matlab-for 234)
    ("teh" "the " nil 16)
    ("cha" "clf; hold on; axis equal; axis off;" nil 5)
    ("\\dis" "disp(sprintf('%0.8g', ))" nil 6)
    ("xxx" "break;" nil 3)
    ("if" "" matlab-if 191)
    ("fch" "figure(1); clf; hold on;" nil 3)
    ("aeo" "axis equal; axis off;" nil 1)
    ("chaa" "clf; hold on; axis equal; axis off" nil 10)
    ("dlr" "dlmread('');" nil 1)
    ("sag" "saveas(gcf, '')" nil 2)
    ("dsr" "display(sprintf('%0.9g'))" nil 1)
    ))

(define-abbrev-table 'fortran-mode-abbrev-table '(
    ))

(define-abbrev-table 'c-mode-abbrev-table '(
    ("while" "while" c-electric-continued-statement 0)
    ("else" "else" c-electric-continued-statement 0)
    ))

(define-abbrev-table 'cperl-mode-abbrev-table '(
    (";u" "undef $/;" nil 0)
    ("sg" "" subst-globally 278)
    ("ssg" "" tilde-subst-globally 42)
    ("\\m" "=~ //" (lambda nil (interacive) (backward-char 1)) 0)
    ("\\cf" "close(FILE);
" cperl-indent-command 77)
    ("opf" "open (FILE, \":utf8\", \"\");" (lambda nil (interactive) (backward-char 3)) 1)
    ("\\f" "<FILE>" nil 10)
    ("\\ud" "undef $/; # undefines the separator. Can read one whole file in one scalar." nil 11)
    ("for" "" perl-for 103)
    ("\\ar" "$ARGV[];" (lambda nil (interactive) (forward-char -2)) 1)
    ("else" "" perl-else 116)
    ("\\ofw" "open(FILE, \">\");" (lambda nil (interactive) (search-backward "\"")) 20)
    ("\\pf" "print FILE \"\\n\";" (lambda nil (interactive) (forward-char -4)) 44)
    ("xxx" "exit(0);" nil 145)
    ("\\ag" "$ARGV[];" (lambda nil (interactive) (forward-char -2)) 1)
    ("if" "" perl-if 313)
    ("\\ofr" "open(FILE, \"<\");" (lambda nil (interactive) (search-backward "\"")) 14)
    ("foreach" "" perl-foreach 163)
    (";x" "exit(0);" nil 0)
    ("print" "" perl-print 558)
    ("\\of" "open (FILE, \":utf8\", \"\");" (lambda nil (interactive) (backward-char 3)) 52)
    ))

(define-abbrev-table 'c++-mode-abbrev-table '(
    ("\\x" "exit(0);" nil 5)
    ("\\vi" "vector<int> " nil 0)
    ("\\ubf" "Util_AssertBool(false);" nil 10)
    ("cin" "cin >> " nil 8)
    ("\\vd" "vector<double> " nil 42)
    ("\\us" "Util_AssertString(\"\");" (lambda nil (interactive) (search-backward "\"")) 1)
    ("\\cl" ".close();" nil 2)
    ("\\p" ".push_back();" (lambda nil (interactive) (search-backward ")")) 0)
    ("\\cd" "complex<double>" nil 8)
    (",." " << endl;" nil 164)
    ("\\ui" "unsigned int " nil 8)
    ("\\f" ".front()" nil 0)
    (",," " << ' ' << " nil 212)
    ("\\e" "endl;" nil 3)
    ("\\c" ".clear();" nil 0)
    ("for" "" c++-for 503)
    ("\\ub" "Util_AssertBool(\"\");" (lambda nil (interactive) (search-backward "\"")) 0)
    ("nii" "new int []" backward-char 4)
    ("teh" "the " nil 23)
    ("while" "while" c-electric-continued-statement 0)
    ("uns" "using namespace std;" nil 8)
    ("else" "else" c-electric-continued-statement 0)
    ("cout" "cout << \"\" << endl;" (lambda nil (interactive) (setq smart_forward_flag 1) (search-backward "\"") (c-indent-command)) 774)
    ("couts" "cout << \"\" << endl;" (lambda nil (interactive) (setq smart_forward_flag 1) (search-backward "\"") (c-indent-command)) 774)
    ("\\pb" ".push_back();" (lambda nil (interactive) (search-backward ")")) 0)
    ("catch" "catch" c-electric-continued-statement 0)
    ("if" "" c++-if 597)
    ("\\sti" "static_cast<int>" nil 11)
    ("\\do" "double " nil 700)
    ("ints" "int*" nil 2)
    ("\\incl" "#include \"\"" backward-char 27)
    ("\\si" ".size()" nil 30)
    ("\\std" "static_cast<double>" nil 11)
    ("\\inc" "#include <>" backward-char 12)
    ("coute" "cout << endl;" nil 0)
    ("\\rs" ".resize()" nil 7)
    ("cerr" "cerr << \"\" << endl;" (lambda nil (interactive) (setq smart_forward_flag 1) (search-backward "\"") (c-indent-command)) 771)
    ))

(define-abbrev-table 'mutt-mode-abbrev-table '(
    ("existance" "existence" nil 2)
    ("htis" "this " nil 0)
    ("hte" "the " nil 7)
    ("continous" "continuous " nil 0)
    ("riguros" "rigoros" nil 0)
    ("taht" "that " nil 14)
    ("wiht" "with " nil 0)
    ))

(define-abbrev-table 'sgml-mode-abbrev-table '(
    ))

(define-abbrev-table 'xml-mode-abbrev-table '(
    ))

(define-abbrev-table 'makefile-mode-abbrev-table '(
    ))

(define-abbrev-table 'temp-buffer-mode-abbrev-table '(
    ))

(define-abbrev-table 'tcl-mode-abbrev-table '(
    ))

(define-abbrev-table 'text-mode-abbrev-table '(
    ("\\cs" "" latex-cases 39)
    ("neib" "neighborhood " nil 14)
    ("\\ro" "\\rho" nil 5)
    ("\\w" "\\wedge " nil 40)
    ("\\r3" "\\mathbb R^3" nil 0)
    ("\\rn" "\\mathbb R^n" nil 3)
    ("\\eco" "\\end{corollary}" nil 1)
    ("\\r2" "\\mathbb R^2" nil 2)
    ("lin" "linearly " nil 0)
    ("\\bco" "\\begin{corollary}" nil 1)
    ("ily" "I love you!" nil 4)
    ("\\t" "\\theta" nil 58)
    ("contr" "contradiction" nil 0)
    ("cin" "cinnps" nil 95)
    ("\\s" "\\sigma" nil 2)
    ("\\ve" "\\varepsilon" nil 138)
    ("\\sol" "\\medskip\\noindent{\\bf Solution.} " nil 37)
    ("\\itm" "" latex-itemize 10)
    ("\\r" "\\mathbb R" nil 82)
    ("\\rem" "\\medskip\\noindent{\\bf Remark.} " nil 1)
    ("\\cim" "\\cimmps" nil 95)
    ("\\q" "\\mathbb Q" nil 2)
    ("coeff" "coefficient " nil 1)
    ("oth" "on the other hand" nil 1)
    ("\\dist" "\\mbox{dist}" nil 3)
    ("\\p" "\\partial " nil 88)
    ("\\o" "\\omega" nil 32)
    ("\\rf" "" latex-ref 422)
    ("\\up" "\\usepackage{}" backward-char 6)
    ("htis" "this " nil 3)
    ("\\efr" "\\end{flushright}" nil 1)
    ("\\ci" "" latex-cite 97)
    ("\\n" "\\noindent" nil 9)
    ("\\eqs" "" (lambda nil (interactive) (insert "\\begin{equation*}
  
\\end{equation*}") (previous-line 1)) 1)
    ("\\re" "\\mathfrak{Re}" nil 7)
    ("\\ft" "\\footnote{}" backward-char 1)
    ("\\prr" "\\medskip\\noindent{\\bf Proof.} " nil 1)
    ("\\bfr" "\\begin{flushright}" nil 1)
    ("rhs" "right-hand side " nil 0)
    ("enviroment" "environment" nil 0)
    ("\\ni" "\\noindent " nil 47)
    ("\\l" "\\lambda" nil 314)
    ("\\fr" "" latex-frac 337)
    ("lhs" "left-hand side " nil 0)
    ("\\k" "\\kappa" nil 0)
    ("\\bv" "\\begin{verbatim}" nil 14)
    ("\\tit" "\\begin{center}\\bf \\end{center}" (lambda nil (interactive) (beginning-of-line) (search-forward "bf ")) 2)
    ("\\bt" "\\begin{tabular}" nil 1)
    ("\\i" "\\infty" nil 127)
    ("\\ne" "\\not=" nil 10)
    ("\\bs" "\\begin{subequations}" nil 13)
    ("\\eca" "\\end{cases}" nil 3)
    ("\\efl" "\\end{flushleft}" nil 2)
    ("\\br" "\\begin{reference}" nil 1)
    ("\\bca" "\\begin{cases}" nil 3)
    ("\\bfl" "\\begin{flushleft}" nil 2)
    ("rigoros" "rigorous " nil 0)
    ("\\g" "\\gamma" nil 26)
    ("\\fl" "\\foilhead{}" (lambda nil (interactive) (backward-char 1)) 8)
    ("hwat" "what " nil 1)
    ("\\emp" "\\emph{}" backward-char 68)
    ("\\na" "\\nabla" nil 4)
    ("\\bp" "" latex-bigg-par 7)
    ("indep" "independent " nil 0)
    ("funs" "functions " nil 0)
    ("htat" "that " nil 5)
    ("\\e" "\\epsilon" nil 7)
    ("polyn" "polynomial " nil 1)
    ("\\ans" "\\medskip\\noindent{\\bf Answer.} 
" nil 6)
    ("\\bfi" "\\begin{figure}" nil 0)
    ("\\d" "\\delta" nil 18)
    ("parameterization" "parametrization " nil 1)
    ("homogenous" "homogeneous " nil 1)
    ("\\efg" "\\end{figure}" nil 7)
    ("\\c" "\\mathbb C" nil 23)
    ("\\eml" "\\end{multline}" nil 3)
    ("\\fh" "\\foilhead{}" backward-char 7)
    ("\\bm" "\\begin{multline*}" nil 5)
    ("\\mn" "\\medskip\\noindent " nil 107)
    ("\\tt" "\\tt " nil 31)
    ("\\bfg" "\\begin{figure}[h]\\label{}" backward-char 6)
    ("\\b" "\\beta" nil 19)
    ("\\a" "\\alpha" nil 126)
    ("\\prob" "\\medskip\\noindent{\\bf Problem .}" (lambda nil (interactive) (backward-char 2)) 18)
    ("\\bl" "\\begin{list}{}" backward-char 3)
    ("approx" "approx " nil 13)
    ("\\bml" "\\begin{multline}" nil 3)
    ("\\transp" "^\\mathsf{T}" nil 0)
    ("props" "properties " nil 0)
    ("\\ker" "\\mbox{Ker}\\," nil 0)
    ("\\ev" "\\end{verbatim}" nil 13)
    ("\\cor" "" latex-corollary 11)
    ("\\ees" "\\end{equation*}" nil 9)
    ("\\lab" "\\label{}" backward-char 19)
    ("\\bi" "\\begin{itemize}" nil 9)
    ("ack" "acknowledgments" nil 0)
    ("\\et" "\\end{tabular}" nil 3)
    ("\\bes" "\\begin{equation*}" nil 6)
    ("\\eeq" "\\end{eqnarray}" nil 5)
    ("\\bh" "\\begin{huge}" nil 1)
    ("\\mi" "\\medskip\\noindent" nil 1)
    ("\\es" "\\end{subequations}" nil 5)
    ("\\pt" "\\partial" nil 6)
    ("\\beq" "\\begin{eqnarray}" nil 4)
    ("\\bg" "" latex-bigg 11)
    ("coeffs" "coefficients " nil 1)
    ("\\im" "\\mathfrak{Im}" nil 4)
    ("\\il" "" latex-int-lim 83)
    ("\\eq" "" latex-equation 78)
    ("\\pr" "" latex-proof 16)
    ("\\een" "\\end{enumerate}" nil 1)
    ("\\be" "\\begin{equation}\\label{}" backward-char 90)
    ("\\mf" "{\\mathbf }" backward-char 26)
    ("\\ep" "\\end{proof}" nil 3)
    ("teh" "the " nil 184)
    ("\\ben" "\\begin{enumerate}" nil 3)
    ("\\bd" "\\begin{definition}" nil 3)
    ("\\els" "\\end{list}" nil 9)
    ("\\pp" "\\Phi" nil 4)
    ("\\bls" "\\begin{list}{}{}" (lambda nil (interactive) (backward-char 3)) 11)
    ("\\bc" "\\begin{center}" nil 29)
    ("\\eth" "\\end{theorem}" nil 1)
    ("\\epm" "\\end{pmatrix}" nil 7)
    ("\\md" "\\medskip" nil 40)
    ("\\ii" "" latex-int 19)
    ("\\en" "" latex-enumerate 11)
    ("\\lt" "{\\LaTeX} " nil 1)
    ("weired" "weird " nil 1)
    ("\\bth" "\\begin{theorem}" nil 2)
    ("\\bpm" "\\begin{pmatrix}" nil 1)
    ("\\bb" "{\\bf }" backward-char 151)
    ("hte" "the " nil 28)
    ("oyu" "you " nil 3)
    ("\\mc" "\\mathcal{}" backward-char 2)
    ("\\em" "\\end{multline*}" nil 8)
    ("\\ls" "" latex-list 18)
    ("\\npi" "\\newpage\\item " nil 9)
    ("\\wt" "\\widetilde " nil 4)
    ("\\lrp" "\\left(\\right)" (lambda nil (interactive) (search-backward "\\")) 2)
    ("\\ba" "\\begin{array}{}" backward-char 16)
    ("\\mb" "\\mbox{  }" (lambda nil (interactive) (backward-char 2)) 115)
    ("\\el" "\\end{list}" nil 3)
    ("\\th" "" latex-theorem 11)
    ("\\p2" "\\frac{\\pi}{2}" nil 12)
    ("\\lr" "\\left(\\right)" (lambda nil (interactive) (search-backward "\\")) 9)
    ("thm" "theorem " nil 2)
    ("\\eal" "\\end{align}" nil 3)
    ("\\elm" "\\end{lemma}" nil 3)
    ("\\ei" "\\end{itemize}" nil 7)
    ("continous" "continuous " nil 2)
    ("\\dy" "\\Delta y" nil 1)
    ("\\sub" "\\subset " nil 15)
    ("\\st" "\\stackrel{\\to}{}" backward-char 32)
    ("\\transpose" "^\\mathsf{T}" nil 0)
    ("\\bib" "\\bibitem{}" backward-char 6)
    ("\\bal" "\\begin{align}" nil 3)
    ("\\blm" "\\begin{lemma}" nil 2)
    ("\\eh" "\\end{huge}" nil 1)
    ("\\dx" "\\Delta x" nil 1)
    ("behaviour" "behavior " nil 15)
    ("\\ss" "\\subsection{}" backward-char 4)
    ("belive" "believe" nil 8)
    ("\\tc" "\\textcolor{}{}" (lambda nil (interactive) (backward-char 3)) 15)
    ("\\l2" " L^2(0,\\infty)" nil 1)
    ("\\lm" "" latex-lemma 15)
    ("\\ef" "\\end{figure}" nil 1)
    ("\\esp" "\\end{split}" nil 13)
    ("\\ll" "\\lim\\limits_{}" backward-char 22)
    ("\\sq" "\\sqrt{}" backward-char 113)
    ("\\bsp" "\\begin{split}" nil 12)
    ("\\ee" "\\end{equation}" nil 70)
    ("\\sp" "" (lambda nil (interactive) (insert "\\begin{split}
  
\\end{split}") (previous-line 1)) 11)
    ("\\ed" "\\end{definition}" nil 1)
    ("\\dt" "\\Delta t" nil 2)
    ("\\eea" "\\end{eqnarray}" nil 1)
    ("\\ec" "\\end{center}" nil 29)
    ("\\li" "Lipschitz" nil 6)
    ("\\ds" "\\displaystyle" nil 2)
    ("riguros" "rigoros" nil 1)
    ("\\bea" "\\begin{eqnarray}" nil 1)
    ("\\baf" "Burden and Faires" nil 10)
    ("\\mbf" "\\mathbf{}" backward-char 6)
    ("\\esl" "\\end{slide}" nil 2)
    ("\\h2" "H^{(2)}_m" nil 4)
    ("\\h1" "H^{(1)}_m" nil 6)
    ("\\hl" "\\\\ \\hline " newline 19)
    ("\\sm" "\\smallskip" nil 3)
    ("param" "parametrization " nil 0)
    ("\\edo" "\\end{document}" nil 3)
    ("\\bsl" "\\begin{slide}" nil 1)
    ("\\ea" "\\end{array}" nil 15)
    ("cyl" "cylindrical" nil 0)
    ("\\sl" "" latex-sum-lim 23)
    ("taht" "that " nil 53)
    ("\\bdo" "\\begin{document}" nil 6)
    ("\\mat" "" latex-matrix 49)
    ("\\pa" "\\paragraph" nil 1)
    ("\\evt" "\\end{verbatim}" nil 4)
    ("wiht" "with " nil 3)
    ("\\eab" "\\end{abstract}" nil 2)
    ("\\toi" "\\to\\infty" nil 1)
    ("\\incl" "\\includegraphics[clip, width=0.8\\textwidth]{}" backward-char 18)
    ("\\bvt" "\\begin{verbatim}" nil 4)
    ("\\hi" "\\phi" nil 155)
    ("\\bab" "\\begin{abstract}" nil 3)
    ("\\eaa" "\\end{eqnarray}" nil 0)
    ("\\vt" "\\vartheta" nil 16)
    ("\\ab" "(\"\" \"\"  0)" (lambda nil (interactive) (beginning-of-line) (search-forward "\"")) 9)
    ("\\om" "\\Omega" nil 21)
    ("\\fra" "" latex-frame 24)
    ("\\ese" "\\end{subequations}" nil 4)
    ("\\abb" "(\"\" \"\" (lambda () (interactive)) 0)" (lambda nil (interactive) (beginning-of-line) (search-forward "\"")) 9)
    ("defence" "defense " nil 3)
    ("responce" "response " nil 1)
    ("prop" "property " nil 0)
    ("\\sss" "\\subsubsection{}" backward-char 4)
    ("analytical" "analytic " nil 3)
    ("\\bse" "\\begin{subequations}" nil 3)
    ("\\di" "\\displaystyle" nil 3)
    ("\\inc" "\\includegraphics[width=0.8\\textwidth]{}" backward-char 3)
    ("\\vp" "\\varphi" nil 35)
    ("\\ny" "\\nyice" nil 96)
    ("\\trans" "^\\mathsf{T}" nil 3)
    ("disp" "displaystyle" nil 14)
    ("\\vec" "" latex-vector 35)
    ("\\ect" "\\end{center}" nil 7)
    ("\\sec" "\\section{}" backward-char 14)
    ("\\sli" "" latex-frame 25)
    ("\\rr" "\\ref{}" backward-char 73)
    ("\\bct" "\\begin{center}" nil 5)
    ("\\z" "\\mathbb Z" nil 19)
    ("\\grad" "\\nabla" nil 17)
    ("\\dd" "\\Delta" nil 1)
    ("\\ct" "" latex-center 28)
    ))

(define-abbrev-table 'lisp-mode-abbrev-table '(
    ("lc" "" local-set-abb 13)
    ("dd" "" lisp-function 17)
    ("gg" "" global-set-abb 7)
    ("\\li" "(lambda () (interacive) )" backward-char 1)
    ("\\ab" "(\"\" \"\"  0)" (lambda nil (interactive) (beginning-of-line) (search-forward "\"")) 0)
    ))

(define-abbrev-table 'help-mode-abbrev-table '(
    ))

(define-abbrev-table 'completion-list-mode-abbrev-table '(
    ))

(define-abbrev-table 'fundamental-mode-abbrev-table '(
    ("\\trk" "set shared::job::dbgTrackKaroList                      {0 }      ;# UD" nil 0)
    ))

(define-abbrev-table 'global-abbrev-table '(
    ))

