;;; perl-my.el --- 

(defun perl-print ()
  (insert "print \"\\n\"\;")
  (backward-char 4)
  )

(defun subst-globally ()
  (interactive)
  (insert "=~ s///g;")
  (backward-char 4)
  )

(defun tilde-subst-globally ()
  (interactive)
  (insert "=~ s///g;")
  (backward-char 4)
  )

(defun perl-foreach ()
  (interactive)
  (save-excursion
    (beginning-of-line)
    (setq empty (looking-at "[ ]*[\t]*[ ]*$")))
  (if (not empty)
      (insert "foreach ")
    (insert "foreach  (){")
    (cperl-indent-command)
    (insert "\n")
    (cperl-indent-command)
    (insert "\n}")
    (cperl-indent-command)
    (previous-line 2)
    (search-forward "(" nil t)
    (backward-char 2)
    ))


(defun insert-square-brackets ()
  (interactive)
  (insert "[]")
  (backward-char 1)
  )

(local-set-key [(control i)] 'indent-region)
(local-set-key [(control t)] nil)
(local-set-key [(control y)] 'yank)
(local-set-key [(meta a)] 'define-mode-abbrev)
(local-set-key [(meta c)] 'comment-region)
(local-set-key [(meta q)] 'kill-this-buffer)
(local-set-key [(meta u)] 'my-uncomment-region)
(local-set-key [(return)] 'reindent-then-newline-and-indent)
(local-set-key [(meta \;)] 'insert-semicolon-and-newline)
(local-set-key [(control j)] 'my-fill-paragraph-or-region)
