bool isDigit(const char);
endif for(int q = 0; q < n;);
int addOne(int);
int deleteAtBeg(list*&);
int deleteOneElem(list*&, int);
int insert(list*&, int);
int myfun1(int, int);
int pop(int &);
int push(int);
int randn(int);
int rmLargestFromHeap(heap &);
void doSort(int *, int, int);
void foo(int);
void formList(list*&, int);
void insertToHeap(heap &, int);
void mergeLists(int *, int, int *, int, int *);
void mergeSort(int *, int, int *);
void myfun1(int);
void printHeap(heap &);
void printInOrderNonRec(node*);
void printList(list *);
void printList2(list *);
void printTree(node *);
void push_back(int);
void push_front(int);
void qsort2(int *, int);
void reverseList(list*&);
void rv_str(char *, int);
void splitAtPivot(list *, int, list*&, list*&);
