#include <iostream>
#include <cmath>
#include <fstream>
#include <algorithm>
#include <vector>
#include <cassert>
#include <cstring>
#include "utils.h"
using namespace std;

std::string utils::getDocText(){

  // Begin auto-generated text
char docText[] ="<div style=\"display:block;text-align:center\"><a href=\"https://sites.google.com/site/olegalexandrov/polyview/polyLogo.png?attredirects=0\" imageanchor=\"1\"><img alt=\"PolyView logo\" src=\"https://sites.google.com/site/olegalexandrov/polyview/polyLogo.png\" border=\"0\"></a></div>\n"
"<br>\n"
"<br>\n"
"<b>PolyView</b>\n"
" is a free and open source software program for Linux designed to quickly load and\n"
" visualize multiple sets of polygon files from the command line. It can \n"
"zoom and pan, show polygons as edges, points, and filled, display text \n"
"labels, print the coordinates of vertices and measure distances, \n"
"change the order in which polygons are displayed, choose which polygons \n"
"to show/hide, etc.<br>\n"
"<br>\n"
"PolyView can also do basic polygon editing, \n"
"such as creating/deleting/moving individual polygons, adding/removing/modifying vertices, as well as \n"
"wholesale changes on the entire set of currently open polygons, such as \n"
"cutting them to a given box or applying shift/scale/rotation \n"
"transformations.<br>\n"
"<br>\n"
"PolyView accepts a lengthy list of command line arguments, and the view can be also manipulated interactively from the GUI once the polygons are loaded. A complete list of features and functions is shown below.<br>\n"
"<br>\n"
"PolyView is implemented in C++ using Qt 4. Its source code is freely available under the MIT license as and can be used for any purpose, academic or commercial.<br>\n"
"<br>\n"
"<h2>Documentation</h2>\n"
"&lt;b&gt;This document describes the features of polyView accessible from<br>\n"
"the GUI and from the command line.&lt;/b&gt;<br>\n"
"<br>\n"
"1. Features of polyView accessible from the GUI<br>\n"
"&nbsp;&nbsp; --------------------------------------------<br>\n"
"<br>\n"
"File menu<br>\n"
"* Load a polygon file in addition to existing files<br>\n"
"* Save the polygons as one file<br>\n"
"* Save the polygons as individual files<br>\n"
"* Overwrite the existing polygons<br>\n"
"<br>\n"
"View menu<br>\n"
"* Choose which files to show/hide<br>\n"
"* Zoom and pan<br>\n"
"* Reset the view to contain all polygons with a small padding<br>\n"
"* Change the order in which the polygons are displayed<br>\n"
"* Show/hide annotations<br>\n"
"* Show polygons as filled with color<br>\n"
"* Show vertices as points<br>\n"
"* Show the index of each vertex<br>\n"
"* Show the layer ids (if present)<br>\n"
"<br>\n"
"Edit menu<br>\n"
"* Undo and redo<br>\n"
"* Create a polygon with integer vertices and edge angles multiple <br>\n"
"&nbsp; of 45 degrees<br>\n"
"* Enforce integer vertices and edge angles multiple of 45 degrees<br>\n"
"* Create a polygon with arbitrary angles<br>\n"
"<br>\n"
"Transform menu<br>\n"
"* Translate/rotate/scale polygons<br>\n"
"<br>\n"
"Selection menu<br>\n"
"* Create a highlight (the polygons in the highlight are automatically<br>\n"
"&nbsp; selected and copied to a buffer)<br>\n"
"* Cut the polygons to the current highlight<br>\n"
"* Delete the selected polygons<br>\n"
"* Paste the selected polygons<br>\n"
"* Move the selected polygons (use Shift-Mouse)<br>\n"
"* Deselect all polygons and delete all highlights<br>\n"
"<br>\n"
"Grid menu<br>\n"
"* Show/hide the grid<br>\n"
"* Enforce that edges have angles multiple of 45 degrees and snap the <br>\n"
"&nbsp; vertices to the grid<br>\n"
"* Set the grid size<br>\n"
"* Set the grid linewidth<br>\n"
"* Set the grid color<br>\n"
"<br>\n"
"Diff menu<br>\n"
"* Change the colors of polygons so that polygons from different files <br>\n"
"&nbsp; have different colors<br>\n"
"* Enter diff mode (a mode in which two similar polygon files can be <br>\n"
"&nbsp; compared)<br>\n"
"* Show the next/previous difference between given two given polygon <br>\n"
"&nbsp; files (starting with the largest difference)<br>\n"
"<br>\n"
"Options menu<br>\n"
"* Set the linewidth of polygon edges<br>\n"
"* Set the background color<br>\n"
"<br>\n"
"Right-click menu<br>\n"
"* Save/show mark at point<br>\n"
"* Use the nm scale when printing the coordinates of vertices <br>\n"
"&nbsp; (assuming that the polygons are at the dbu scale)<br>\n"
"* Create a polygon with integer vertices and edge angles multiple <br>\n"
"&nbsp; of 45 degrees<br>\n"
"* Enforce integer vertices and edge angles multiple of 45 degrees<br>\n"
"* Create a polygon with arbitrary angles<br>\n"
"* Delete the polygon at mouse cursor<br>\n"
"* Enter align mode (a mode in which, given two polygon files, the <br>\n"
"&nbsp; second polygon file is kept fixed, while the first one can be <br>\n"
"&nbsp; interactively shifted using Shift-Mouse and rotated/flipped from <br>\n"
"&nbsp; the right-click menu until it aligns to the second one)<br>\n"
"* Enter move polygons mode (use Shift-Mouse to move a polygon)<br>\n"
"* Enter move vertices mode (use Shift-Mouse to move a vertex)<br>\n"
"* Enter move edges mode (use Shift-Mouse to move an edge)<br>\n"
"* Insert a vertex on the edge closest to the mouse cursor<br>\n"
"* Delete the vertex closest to the mouse cursor<br>\n"
"* Copy the polygon closest to the mouse cursor<br>\n"
"* Paste the polygon closest to the mouse cursor<br>\n"
"* Reverse the orientation of the polygon closest to the mouse cursor<br>\n"
"<br>\n"
"2. Features of polyView accessible from the command line<br>\n"
"&nbsp;&nbsp; -----------------------------------------------------<br>\n"
"<br>\n"
"polyView will open simultaneously all polygon files supplied as inputs<br>\n"
"on the command line. Various command line options can modify how the<br>\n"
"polygons are displayed.<br>\n"
"<br>\n"
"-h | -help&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Show the available command line <br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; options<br>\n"
"&nbsp;&nbsp; <br>\n"
"-geo[metry] (for example 1000x800)&nbsp;&nbsp; The window size in pixels<br>\n"
"<br>\n"
"-bg | -backgroundColor &lt;color name&gt;&nbsp; Color of the background (default is black)<br>\n"
"<br>\n"
"-c | -color &lt;color name&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; All polygons after this option will show<br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; up in the given color<br>\n"
"<br>\n"
"-fs | -fontSize &lt;integer&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The text font size in pixels<br>\n"
"<br>\n"
"-lw | -lineWidth &lt;integer&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; All polygons after this option will show<br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; up with given linewidth<br>\n"
"<br>\n"
"-p | -points&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; All polygons after this option will show<br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; up as points (a subsequent -p option undoes<br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; the previous one)<br>\n"
"<br>\n"
"-cp | -closedPoly&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; All polygons after this option will show <br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; up as closed (the last vertex is connected<br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; to the first vertex)<br>\n"
"<br>\n"
"-nc | -nonClosedPoly&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Interpret the vertices as belonging to a <br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; polygonal line rather than to a polygon<br>\n"
"<br>\n"
"-f | -filledPoly&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; All polygons after this option will show<br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; up as filled<br>\n"
"<br>\n"
"-nf | -nonFilledPoly&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; All polygons after this option will show <br>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; up as not filled<br>\n"
"<br>\n"
"-grid on | off&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Turn on/off the grid display<br>\n"
"<br>\n"
"-gridSize &lt;integer&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Grid size<br>\n"
"<br>\n"
"-gridWidth &lt;integer&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Grid width in pixels<br>\n"
"<br>\n"
"-gridColor &lt;color&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Grid color<br>\n"
"<br>\n"
"<b>Author's contact information: </b>oleg.alexandrov at gmail.com<br>\n"
"<b><br>\n"
"<br>\n"
"</b><br>\n"
"<br>\n"
"<br>\n"
"<br>\n";
  // End auto-generated text
 return docText;
}









