#!/usr/bin/perl
use strict;                   # 'strict' insists that all variables be declared
use diagnostics;              # 'diagnostics' expands the cryptic warnings
undef $/; # undefines the separator. Can read one whole file in one scalar.

# Package a command in a form acceptable to gdb

MAIN:{

  if (scalar (@ARGV) <= 0  ){
    print "Usage: program_name program_arguments\n";
    exit(0);
  }

  my $prog_name = shift (@ARGV);
  my $prog_args  = join (" ", @ARGV);

  my $gdb_file    = "run.gdb";
  my $gdb_command = "run $prog_args";
  
  open(FILE, ">$gdb_file");
  print FILE "$gdb_command\n";
  close(FILE);

  # Deal with the pecularities of the build system
  $prog_name =~ s/^(.*\/)(.*?)$/$1Linux_debug_64\/$2/g;

  # Run gdb on given program with commands from $gdb_file
  print "\n";
  print "gdb $prog_name -x $gdb_file\n";
  print "$gdb_command\n";
  print "\n";
  
  system("gdb $prog_name -x $gdb_file\n");
  
}
