#!/usr/bin/perl
use strict;	   # insist that all variables be declared
use diagnostics;   # expand the cryptic warnings
undef $/;          # read one whole file in one scalar

MAIN:{

  # Find the full path to a file
  
  if (scalar(@ARGV) < 1){
    print "Usage: $0 fileName\n";
    exit(0);
  }

  my $file = $ARGV[0];

  if ($file !~ /^\//){
    my $dir = qx(pwd);
    $dir =~ s/\s*$//g;
    $file = $dir . '/' . $file;
  }

  while ( $file =~ /^(.*?\/)([^\/]*?\/\.\.\/)(.*?)$/ ){
    $file = $1 . $3;
  }
    
  $file =~ s/[\/]+/\//g;
  
  print "$file\n";
}
