#!/bin/bash

#run_loc="ssh aps-titan";
run_loc="";

#export XEPATH=/grid/common/pkgs/xemacs/v21.4.20/bin/
export XEPATH=/home/olegalex/xemacs/bin/
instanceCount=$(ps aux | grep `whoami` | grep xemacs | grep -v 'grep xemacs' | wc -l);
if [ "$instanceCount" -eq "0" ]; then

  $XEPATH/xemacs -geo 90x32+0+0 &
  instanceCount="";
  
  while [ "$instanceCount" = "" ]; do
    instanceCount=$(ps aux | grep `whoami` | grep gnuserv | grep -v 'grep gnuserv' | wc -l);
    echo "waiting for gnuserv";
    sleep 1;
  done;

  sleep 1;

else
  
  $XEPATH/gnuclient -q $* &

fi




