#!/usr/bin/perl
use strict;                   # 'strict' insists that all variables be declared
use diagnostics;              # 'diagnostics' expands the cryptic warnings
undef $/; # undefines the separator. Can read one whole file in one scalar.

# Transform 
#      cvm add new stuff myfile.cpp myfile.h 
# into
#      cvs commit -m "add new stuff" myfile.cpp myfile.h

MAIN:{
  
  my ($command, $subject, $files, $token);

  if (-d "CVS"){
    $command = "cvs";
  }elsif (-d ".svn"){
    $command = "svn";
  }
  
  $subject = "";
  $files   = "";
  
  foreach $token (@ARGV){

    if (-e $token){
      $files   = $files . " " . $token;
    }else{
      $subject = $subject . " " . $token;
    }
  }

  $files   =~ s/^\s*//g;
  $subject =~ s/^\s*//g;

  if ($subject !~ /^\s*$/){

    $command = "$command commit -m '$subject' $files";
    print "$command\n";
    print `$command`;
    
  }else{
    
    print "Cannot commit with an empty subject\n";
    
  }
  
}
