#!/bin/bash

# Add a directory recursively to CVS.

# Usage: cvs_rec topDirName

if [ "$#" -ne "1" ]; then
  echo "Usage: $(basename $0) topDirName"
  exit 1;
fi

# Add recursively to CVS
topDirName=$1

# First remove the "CVS" subdirectories  
cvsDirs=$( find $topDirName -name CVS )
for cvsDir in $cvsDirs; do
    rm -rfv $cvsDir
done

files=$( find $topDirName | grep -v CVS )
for file in $files; do
  cvs add $file
done