#!/usr/bin/perl
use strict;                   # 'strict' insists that all variables be declared
use diagnostics;              # 'diagnostics' expands the cryptic warnings
undef $/; # undefines the separator. Can read one whole file in one scalar.

# Package a command in a form acceptable to valgrind

MAIN:{

  if (scalar (@ARGV) <= 0  ){
    print "Usage: program_name program_arguments\n";
    exit(0);
  }

  my $prog_name = shift (@ARGV);
  my $prog_args  = join (" ", @ARGV);

  # Deal with the pecularities of the build system
  $prog_name =~ s/^(.*\/)(.*?)$/$1Linux_debug_64\/$2/g;

  my $vg_prog = $ENV{HOME} . "/bin/valgrind";
  my $vg_opts = "--log-file=Log --leak-check=full";
  
  my $vg_command = "$vg_prog $vg_opts $prog_name $prog_args\n";

  print "\n";
  print "$vg_command\n";
  print "\n";
  system("$vg_command");
  
  
}
